### ISSUE TITLE
Cannot load monitor profile

### ISSUE THREAD

**Issue by lazysquid** [marco-o/LIBICCPP#1]
Hello I was trying to load my icm file and apply CMS to images using this library.

So I tried like this.

``` CPP
using BYTE = unsigned char;

std::unique_ptr<iccpp::profile_t> profile_monitor1
(iccpp::profile_t::create("../assets/leftmonitor.icc"));
std::unique_ptr<iccpp::profile_t> profile_sRGB
(iccpp::profile_t::create_sRGB());


iccpp::function_t<iccpp::xyz_t, iccpp::rgb_t<BYTE>> sRGB2xyz =
    profile_sRGB->device2pcs<iccpp::xyz_t, iccpp::rgb_t<BYTE>>();
iccpp::function_t<iccpp::rgb_t<BYTE>, iccpp::xyz_t > xyz2sRGB =
    profile_sRGB->pcs2device<iccpp::rgb_t<BYTE>, iccpp::xyz_t>();
iccpp::function_t<iccpp::xyz_t, iccpp::rgb_t<BYTE>> monitorOne2xyz =
    profile_monitor1->device2pcs<iccpp::xyz_t, iccpp::rgb_t<BYTE>>();
iccpp::function_t<iccpp::rgb_t<BYTE>, iccpp::xyz_t > xyz2monitorOne =
    profile_monitor1->pcs2device<iccpp::rgb_t<BYTE>, iccpp::xyz_t>();
```

 profile_sRGB and functions that are generated by it works really nice.
However profile that is created using my monitor's profile and functions which is profile_monitor1 and monitorOne2xyz  and xyz2monitorOne seems not working.
I generated my icm file using Spyder5.

Actually imp_ of monitorOne2xyz  and xyz2monitorOne are empty.
So I think there are some problem in code or my icc files. 
Is there any problem in my code? Or am i missing something?

**Comment by marco-o** [comment]
There may be a problem in my code as well, it had not been deeply tested.
Can you attach your profile so I can test my code with it?
Il 11/Lug/2016 08:22, "FrostedPenguin" notifications@github.com ha
scritto:

Hello I was trying to load my icm file and apply CMS to images.

So I tried like this.
`
std::unique_ptriccpp::profile_t profile_monitor1
(iccpp::profile_t::create("../assets/leftmonitor.icc"));
std::unique_ptriccpp::profile_t profile_sRGB
(iccpp::profile_t::create_sRGB());
profile_monitor1->load_all();

iccpp::function_t> sRGB2xyz =
profile_sRGB->device2pcs>();
iccpp::function_ticcpp::rgb_t<BYTE, iccpp::xyz_t > xyz2sRGB =
profile_sRGB->pcs2deviceiccpp::rgb_t<BYTE, iccpp::xyz_t>();
iccpp::function_t> monitorOne2xyz =
profile_monitor1->device2pcs>();
iccpp::function_ticcpp::rgb_t<BYTE, iccpp::xyz_t > xyz2monitorOne =
profile_monitor1->pcs2deviceiccpp::rgb_t<BYTE, iccpp::xyz_t>();
`
profile_sRGB and functions that are generated by it works really nice.
However profile that is created using my monitor's profile and functions
which is profile_monitor1 and monitorOne2xyz and xyz2monitorOne seems not
working.
I generated my icm file using Spyder5.

Actually imp_ of monitorOne2xyz and xyz2monitorOne are empty.
So I think there are some problem in code or my icc files.
Is there any problem in my code? Or am i missing something?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/marco-o/LIBICCPP/issues/1, or mute the thread
https://github.com/notifications/unsubscribe/AKR17YifFCurg0ZAR-uCV4_dNXXXOWTWks5qUeEmgaJpZM4JJEGO
.

**Comment by lazysquid** [comment]
RGB space of my source images are assumed as a sRGB 
and my target RGB space is my monitor profile which is this.
https://www.dropbox.com/s/d02j607ay3ocon2/Leftmonitor.icm?dl=0

And I'm quite new to CMS but as far as I know there are no differences between icm and icc.
However I just convert it to icc so you can use either of them.

https://www.dropbox.com/s/o3znxqt1xyzwtki/E2441-1.icc?dl=0

**Comment by marco-o** [comment]
Your files are ok, it's my library that is unable to handle them
Unfortunately I am rather busy at the momento so I cannot tell you when
I'll fix it.
You are better off give a look at anther lib.
